name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main # Dispara o deploy automático ao fazer push para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Define que este job utiliza o ambiente (Environment) de 'production' no GitHub
    environment: production
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Executar Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        # Usa 'vars' para variáveis públicas e 'secrets' para dados criptografados (SSH_KEY)
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # 1. Navegar até o diretório do projeto na VM
          cd ${{ vars.WORK_DIR }}
          
          # 2. Atualizar o código a partir do repositório Git
          git pull origin main
          
          # 3. Aplicar os manifestos de infraestrutura e mocks atualizados no Kubernetes (Kind)
          kubectl apply -f k8s/frontend-deploy.yaml
          kubectl apply -f k8s/api-mocks-deploy.yaml
          kubectl apply -f k8s/ingress.yaml
          
          # 4. Aplicar os emissores do Cert-Manager (SSL/TLS)
          if [ -d "k8s/cert-manager" ]; then
            kubectl apply -f k8s/cert-manager/
          fi
          
          echo "Deploy finalizado com sucesso em $(date)"
